### ISSUE TITLE
This line switches the argument order

### ISSUE THREAD

**Issue by jvsteiner** [vansante/go-dl-stream#6]
https://github.com/vansante/go-dl-stream/blob/8d79b08175c7715da94c82ba416a58b3ee14ae34/download.go#L85

It makes it so the `filePath` comes before `url` in `DownloadStream` despite being documented the other way.

**Comment by vansante** [comment]
Good catch, that is not how it should be!

**Comment by vansante** [comment]
I have fixed it in #7 which will be included in the first v2.x release. (Changing this will be a backwards incompatible change, even though its very much a bug :disappointed: )

**Comment by vansante** [comment]
This should be resolved when using v2 of the package:

`go get gopkg.in/vansante/go-dl-stream.v2@v2.0.1`
